# Generated by Django 5.2.6 on 2025-09-21 03:59

import books.mixins
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Full file path', max_length=1000)),
                ('file_path_hash', models.CharField(default='', editable=False, max_length=64, unique=True)),
                ('file_format', models.CharField(choices=[('epub', 'EPUB'), ('mobi', 'MOBI'), ('pdf', 'PDF'), ('cbr', 'CBR'), ('cbz', 'CBZ'), ('placeholder', 'Placeholder')], max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('cover_path', models.CharField(blank=True, help_text='Local cover file path', max_length=1000)),
                ('opf_path', models.CharField(blank=True, help_text='OPF metadata file path', max_length=1000)),
                ('first_scanned', models.DateTimeField(auto_now_add=True)),
                ('last_scanned', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_placeholder', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_corrupted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-last_scanned', 'file_path'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Filename', 'Filename'), ('EPUB', 'EPUB'), ('MOBI', 'MOBI'), ('PDF', 'PDF'), ('OPF File', 'OPF File'), ('Open Library', 'Open Library'), ('Google Books', 'Google Books'), ('Comic Vine', 'Comic Vine'), ('Open Library Covers', 'Open Library Covers'), ('Google Books Covers', 'Google Books Covers'), ('Original Scan', 'Original Scan'), ('Manual Entry', 'Manual Entry'), ('content_scan', 'Content Scan')], max_length=50, unique=True)),
                ('trust_level', models.FloatField(default=0.5, help_text='Trust level for this source (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'ordering': ['-trust_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_reviewed', models.BooleanField(default=False, help_text="Mark genres you've verified or finalized")),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_reviewed', models.BooleanField(default=False, help_text="Mark publishers you've verified or finalized")),
            ],
        ),
        migrations.CreateModel(
            name='ScanFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('content_type', models.CharField(choices=[('ebooks', 'Ebooks'), ('comics', 'Comics'), ('audiobooks', 'Audiobooks'), ('mixed', 'Mixed Content')], default='ebooks', help_text='Type of content in this scan folder', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('nl', 'Dutch'), ('es', 'Spanish'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese'), ('ru', 'Russian'), ('pl', 'Polish'), ('he', 'Hebrew'), ('hu', 'Hungarian'), ('tr', 'Turkish'), ('ca', 'Catalan'), ('id', 'Indonesian')], default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_processed_file', models.TextField(blank=True, help_text='Last file path that was completely processed', null=True)),
                ('total_files', models.IntegerField(default=0, help_text='Total number of files to process')),
                ('processed_files', models.IntegerField(default=0, help_text='Number of files processed so far')),
                ('scan_folders', models.TextField(blank=True, help_text='JSON list of folders being scanned', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('name_normalized', models.CharField(db_index=True, max_length=200, unique=True)),
                ('is_reviewed', models.BooleanField(default=False, help_text="Mark authors you've verified or finalized")),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_author_name_combo')],
            },
        ),
        migrations.CreateModel(
            name='FileOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('rename', 'File Rename'), ('move', 'File Move'), ('create_folder', 'Folder Creation')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reverted', 'Reverted')], default='pending', max_length=20)),
                ('original_file_path', models.CharField(blank=True, max_length=1000)),
                ('original_cover_path', models.CharField(blank=True, max_length=1000)),
                ('original_opf_path', models.CharField(blank=True, max_length=1000)),
                ('original_folder_path', models.CharField(blank=True, max_length=1000)),
                ('new_file_path', models.CharField(blank=True, max_length=1000)),
                ('new_cover_path', models.CharField(blank=True, max_length=1000)),
                ('new_opf_path', models.CharField(blank=True, max_length=1000)),
                ('new_folder_path', models.CharField(blank=True, max_length=1000)),
                ('additional_files', models.TextField(default='[]', help_text='JSON list of additional files moved')),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.UUIDField(blank=True, help_text='Groups operations from same batch', null=True)),
                ('notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_operations', to='books.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'books_fileoperation',
                'ordering': ['-operation_date'],
            },
        ),
        migrations.CreateModel(
            name='FinalMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_title', models.CharField(blank=True, max_length=500)),
                ('final_title_confidence', models.FloatField(default=0.0)),
                ('final_author', models.CharField(blank=True, max_length=500)),
                ('final_author_confidence', models.FloatField(default=0.0)),
                ('final_series', models.CharField(blank=True, max_length=200, null=True)),
                ('final_series_number', models.CharField(blank=True, max_length=20, null=True)),
                ('final_series_confidence', models.FloatField(default=0.0)),
                ('final_cover_path', models.CharField(blank=True, max_length=1000)),
                ('final_cover_confidence', models.FloatField(default=0.0)),
                ('final_publisher', models.CharField(blank=True, max_length=200)),
                ('final_publisher_confidence', models.FloatField(default=0.0)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('completeness_score', models.FloatField(default=0.0)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('has_cover', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='scan_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.scanfolder'),
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('scan_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.scanfolder')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('flatly', 'Flatly'), ('cosmo', 'Cosmo'), ('bootstrap', 'Bootstrap Default'), ('cerulean', 'Cerulean'), ('cyborg', 'Cyborg'), ('darkly', 'Darkly'), ('journal', 'Journal'), ('litera', 'Litera'), ('lumen', 'Lumen'), ('lux', 'Lux'), ('materia', 'Materia'), ('minty', 'Minty'), ('morph', 'Morph'), ('pulse', 'Pulse'), ('quartz', 'Quartz'), ('sandstone', 'Sandstone'), ('simplex', 'Simplex'), ('sketchy', 'Sketchy'), ('slate', 'Slate'), ('solar', 'Solar'), ('spacelab', 'Spacelab'), ('superhero', 'Superhero'), ('united', 'United'), ('vapor', 'Vapor'), ('yeti', 'Yeti'), ('zephyr', 'Zephyr')], default='flatly', help_text='Selected Bootswatch theme', max_length=20)),
                ('items_per_page', models.IntegerField(default=50, help_text='Number of items to show per page')),
                ('show_covers_in_list', models.BooleanField(default=True, help_text='Show book covers in list views')),
                ('default_view_mode', models.CharField(choices=[('table', 'Table'), ('grid', 'Grid')], default='table', help_text='Default view mode for lists', max_length=10)),
                ('share_reading_progress', models.BooleanField(default=False, help_text='Share reading progress with other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'books_userprofile',
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(help_text='Original filename used for AI prediction', max_length=500)),
                ('ai_predictions', models.TextField(help_text='JSON of AI predictions for each field')),
                ('prediction_confidence', models.FloatField(blank=True, help_text='Overall AI prediction confidence', null=True)),
                ('user_corrections', models.TextField(help_text='JSON of user corrections to AI predictions')),
                ('feedback_rating', models.IntegerField(choices=[(1, 'Poor - Completely wrong'), (2, 'Fair - Some correct elements'), (3, 'Good - Mostly correct'), (4, 'Very Good - Almost perfect'), (5, 'Excellent - Perfect prediction')], help_text='User rating of AI prediction quality')),
                ('comments', models.TextField(blank=True, help_text='Additional user feedback or comments')),
                ('needs_retraining', models.BooleanField(default=True, help_text='Whether this feedback should be used for retraining')),
                ('processed_for_training', models.BooleanField(default=False, help_text='Whether this feedback was used in training')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='books.book')),
            ],
            options={
                'db_table': 'books_aifeedback',
                'ordering': ['-created_at'],
                'unique_together': {('book', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BookTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this metadata without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='books.book')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.datasource')),
            ],
            options={
                'ordering': ['-confidence'],
                'unique_together': {('book', 'title', 'source')},
            },
            bases=(books.mixins.FinalMetadataSyncMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BookMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField()),
                ('field_value_hash', models.CharField(editable=False, max_length=64)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to ignore this metadata field for selection and display.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='books.book')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.datasource')),
            ],
            options={
                'ordering': ['-confidence'],
                'unique_together': {('book', 'field_name', 'field_value_hash', 'source')},
            },
            bases=(books.mixins.FinalMetadataSyncMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_path', models.CharField(help_text='Local file path or URL', max_length=1000)),
                ('cover_path_hash', models.CharField(editable=False, max_length=64)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, help_text='jpg, png, gif, etc.', max_length=10)),
                ('is_high_resolution', models.BooleanField(default=False)),
                ('aspect_ratio', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this metadata without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='books.book')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.datasource')),
            ],
            options={
                'ordering': ['-confidence', '-is_high_resolution', '-width'],
                'unique_together': {('book', 'cover_path_hash', 'source')},
            },
            bases=(books.mixins.FinalMetadataSyncMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_main_author', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this metadata without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookauthor', to='books.book')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.datasource')),
            ],
            options={
                'ordering': ['-confidence', '-is_main_author'],
                'unique_together': {('book', 'author', 'source')},
            },
            bases=(books.mixins.FinalMetadataSyncMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookgenre', to='books.book')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.datasource')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genre')),
            ],
            options={
                'unique_together': {('book', 'genre', 'source')},
            },
        ),
        migrations.CreateModel(
            name='BookPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this metadata without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookpublisher', to='books.book')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.datasource')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_books', to='books.publisher')),
            ],
            options={
                'ordering': ['-confidence'],
                'unique_together': {('book', 'publisher', 'source')},
            },
            bases=(books.mixins.FinalMetadataSyncMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_number', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this metadata without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_info', to='books.book')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.datasource')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.series')),
            ],
            options={
                'verbose_name_plural': 'Book Series',
                'ordering': ['-confidence'],
                'unique_together': {('book', 'series', 'source')},
            },
            bases=(books.mixins.FinalMetadataSyncMixin, models.Model),
        ),
    ]
