# Generated by Django 5.2.6 on 2026-09-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalmetadata",
            name="accuracy_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name="finalmetadata",
            index=models.Index(fields=["accuracy_score"], name="books_final_accurac_6e4b62_idx"),
        ),
    ]
