# Generated by Django 5.2.6 on 2026-09-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_finalmetadata_accuracy_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalmetadata',
            name='unresolved_reason',
            field=models.CharField(blank=True, choices=[('uncertain', 'Uncertain match'), ('unmapped_series', 'Unmapped series'), ('no_match', 'No matching candidate'), ('neither_source', 'Neither source resolved')], default='', max_length=20),
        ),
    ]
