# Generated by Django 5.2.6 on 2026-09-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_finalmetadata_unresolved_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanfolder",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not defined"),
                    ("en", "English"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("nl", "Dutch"),
                    ("es", "Spanish"),
                    ("it", "Italian"),
                    ("pt", "Portuguese"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("zh", "Chinese"),
                    ("ru", "Russian"),
                    ("pl", "Polish"),
                    ("he", "Hebrew"),
                    ("hu", "Hungarian"),
                    ("tr", "Turkish"),
                    ("ca", "Catalan"),
                    ("id", "Indonesian"),
                    ("und", "Undetermined"),
                ],
                default="",
                help_text="Default language for books in this folder (used for API searches if not specified in metadata)",
                max_length=10,
            ),
        ),
    ]
